### ISSUE TITLE
Add packages to official OpenWrt repos?

### ISSUE THREAD

**Issue by roger-** [nanpuyue/openwrt-extra#2]
Any interest in adding these packages (particularly the Aria2 stuff) to the OpenWrt [package feed](https://github.com/openwrt/packages)?

I'd be happy to make the pull request if you like.

Thanks!

**Comment by nanpuyue** [comment]
It's a good idea.

**Comment by roger-** [comment]
Thanks. Would you like me to make the pull request?

**Comment by nanpuyue** [comment]
No problem.

**Comment by roger-** [comment]
@nanpuyue 

Do you mind if I keep you as the package maintener when I add them?

**Comment by nanpuyue** [comment]
No, of course not.
